// Small shared bits reused across every step panel — kept here instead of
// duplicated per-step so the "card" and "recommendation badge" look stays
// identical across Design/QC/Normalize/Alpha/Beta/Differential/Summary.
import type { ReactNode } from "react";

export function Card({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <div className={`rounded-2xl border border-slate-200/80 bg-slate-50/60 p-5 ${className}`}>{children}</div>;
}

export function Stat({ label, value }: { label: string; value: ReactNode }) {
  return (
    <div>
      <dt className="text-xs text-slate-500">{label}</dt>
      <dd className="mt-0.5 text-sm font-medium text-slate-900">{value}</dd>
    </div>
  );
}

// The reviewer's recommended option — same green "AI proposal" language
// across every gate.
export function RecBadge({ label }: { label: string }) {
  return (
    <span className="inline-flex items-center gap-1.5 rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">
      <SparkleIcon /> {label}
    </span>
  );
}

export function SparkleIcon() {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="h-3.5 w-3.5">
      <path d="M12 3l1.8 4.3L18 9l-4.2 1.7L12 15l-1.8-4.3L6 9l4.2-1.7L12 3Z" strokeLinejoin="round" />
      <path d="M19 15l.9 2.1L22 18l-2.1.9L19 21l-.9-2.1L16 18l2.1-.9L19 15Z" strokeLinejoin="round" />
    </svg>
  );
}

// The reviewer's free-text reasoning, generated with inline <b>/<span
// class="mono"> markup — same approach the source app uses. Content is
// always generated by gut-pilot's own backend, never user input.
export function GateNote({ html }: { html: string | null | undefined }) {
  if (!html) return null;
  return (
    <div
      className="rounded-xl border border-blue-100 bg-blue-50/50 p-4 text-sm leading-relaxed text-slate-700 [&_.mono]:font-mono [&_.mono]:text-xs [&_b]:font-semibold [&_b]:text-slate-900"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

export function SectionHeading({ title, lede }: { title: string; lede: string }) {
  return (
    <div>
      <h3 className="text-lg font-semibold tracking-tight text-slate-900">{title}</h3>
      <p className="mt-1 max-w-[65ch] text-sm text-slate-600">{lede}</p>
    </div>
  );
}

export function fmt(n: number): string {
  return n.toLocaleString("en-US");
}

export function pct(n: number): string {
  return (n * 100).toFixed(1) + "%";
}
